#! /bin/sh
#
# Auto-detect monitor set up
# Used for configuring "bspwm"

internal_monitor=eDP-1
# external_monitor=DP-1

external_monitor_as_primary_only() {
  local external_monitor_name=$(xrandr -q | grep -w 'connected' | grep -v "$internal_monitor" | grep -Po '^[-\w]+')

	xrandr --output "$external_monitor_name" --primary --auto --output "$internal_monitor" --off
	# xrandr --output DP-1 --primary --mode 3440x1440 --pos 0x0 --rotate normal --output eDP-1 --off --output HDMI-1 --off --output DP-2 --off
}

laptop_monitor_as_primary_only() {
	xrandr --output "$internal_monitor" --primary --auto
}

num_displays_connected=$(xrandr -q | grep -w 'connected' | wc -l)

if [[ $num_displays_connected -gt 1 ]]; then
    external_monitor_as_primary_only
else
	laptop_monitor_as_primary_only
fi
