add_newline = true
format = "$all$line_break$directory$git_branch$git_commit$git_metrics$line_break$character"

[cmd_duration]
format = "[$duration]($style) "

[git_commit]
only_detached = false

[git_metrics]
disabled = false

[git_status]
disabled = true

[hostname]
disabled = true

[kubernetes]
disabled = false

[python]
format = "[$virtualenv]($style) "

