"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = "$all$line_break$directory$git_branch$git_commit$git_metrics$line_break$character"
# right_format = "$aws"

# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $cmd_duration\
# $line_break\
# $pulumi\
# $kubernetes\
# $character"""

palette = 'gruvbox_dark'

[aws]
symbol = "AWS/"
format = '[($profile )(\($region\) )(\[$duration\] )]($style)'

[pulumi]
format ='[$symbol$stack]($style) '

[nodejs]
format = '[$symbol($version )]($style)'

[cmd_duration]
format = "[$duration]($style) "

[git_commit]
only_detached = false

[git_metrics]
disabled = false

[git_status]
disabled = true

[hostname]
disabled = true

[kubernetes]
disabled = false

[python]
format = "[$virtualenv]($style) "

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
