#!/bin/bash
#
# Based on: https://github.com/altrgeek/bspwm-polybar/

## Environment
export PATH="$HOME/.config/.scripts:${PATH}"
export PATH="$HOME/.config/bspwm:${PATH}"
export PATH="$HOME/.config/polybar:${PATH}"

# ## Coloring
# getcolors () {
#   FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
#   BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
#   BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
#   RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
#   GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
#   YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
#   BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
#   MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
#   CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
#   WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
# }
# # xrdb ~/.Xresources
# COLOR=$(shuf -n1 -e $HOME/.config/.colors/*)
# xrdb -merge $COLOR


## Bspwm configurations
bspc monitor -d '1' '2' '3'
bspc config focus_follows_pointer true

bspc config split_ratio     0.52
bspc config border_width    2
bspc config window_gap      8
bspc config top_padding     0
bspc config right_padding   5
bspc config bottom_padding  5
bspc config left_padding    5

bspc config focused_border_color  "#E57C46"
# bspc config normal_border_color   "$BLACK"
# bspc config active_border_color   "$MAGENTA"
bspc config presel_feedback_color "#3F5360"

bspc config borderless_monocle        true
bspc config gapless_monocle           false
bspc config paddingless_monocle       false
bspc config single_monocle            true
bspc config remove_disabled_monitors  true


## Window rules
# remove all rules first
bspc rule -r *:*

bspc rule -a Slack desktop='^3' follow=on focus=on
bspc rule -a Spotify desktop='^3' follow=on focus=on

#1 > terminal
# bspc rule -a URxvt desktop='^1' follow=on focus=on
#2 > web
# bspc rule -a Chromium desktop='^2' follow=on focus=on
#3 > file
# bspc rule -a Thunar desktop='^3' follow=on focus=on
# bspc rule -a Dolphin desktop='^3' follow=on focus=on
# bspc rule -a Nautilus desktop='^3' follow=on focus=on
# bspc rule -a File-roller desktop='^3' follow=on focus=on

#4 > office
#declare -a office=(wpp wps et gedit)
#for i in ${office[@]}; do
 #bspc rule -a $i desktop='^4' follow=on focus=on

#5 > media
#declare -a media=(Audacity mpv Gimp Gimp-2.8)
#for i in ${media[@]}; do
 #  bspc rule -a $i desktop='^5' follow=on focus=on; done
# bspc rule -a Gedit desktop='^4' follow=on focus=on
# bspc rule -a Audacious desktop='^5' follow=on focus=on
# bspc rule -a vlc desktop='^5' follow=on focus=on
# bspc rule -a Gimp desktop='^5' follow=on focus=on
# bspc rule -a Spotify desktop='^5' follow=on focus=on

#6 > settings

## Misc
# declare -a settings=(Lxappearance Lxtask Lxrandr Arandr System-config-printer.py Pavucontrol Exo-helper-1)
# for i in ${settings[@]}; do
#    bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done
# bspc rule -a GParted desktop='^6' follow=on focus=on

#special rules
# bspc rule -a Audacious state=floating follow=on focus=on
# bspc rule -a Chromium state=floating follow=on focus=on
# bspc rule -a Viewnior state=floating follow=on focus=on

## Autostart
killall -9 sxhkd xsettingsd dunst
xsetroot -cursor_name left_ptr
xbacklight -set 10

xset fp+ $HOME/.config/.fonts/               # Load fonts in X

setup_monitors

sxhkd &       # hotkey bindings
launch.sh     # polybar
xsettingsd &
dunst &
# dunst \
#   -lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$GREEN" \
#   -nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
#   -cb "$BACKGROUND" -cf "$FOREGROUND" -cfr "$RED" &

# set Wallpaper
hsetroot -fill $HOME/.config/wallpapers/bg_5.jpg &
sleep 0.5

notify-send "Bspwm Loaded"
